Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EventManagement.Controllers
{
    public class EventController : Controller
    {
        // GET: Event
        public ActionResult Index()
        {
            return View();
        }
    }
}

Views/Attendance/Create.cshtml
@model EventManagement.Models.AttendanceQRModel



<div class="note note-info">
    <h4 class="block">
        Create Event Attendance
    </h4>
    <a href="/Event/Detail/@Model.EventID" class="btn blue btn-sm">Back to Event</a>
</div>

@Html.Action("EventSummary", "Event", new { ID = Model.EventID })


<div class="portlet box blue tabbable">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-reorder"></i>Event Attendance Details
        </div>
    </div>
    <div class="portlet-body form">
        <div class=" portlet-tabs">

            <div class="tab-content">

                <div class="tab-pane active" id="support_detail">
                    <!--START NOTIFICATION HISTORY-->
                    <div class="portlet-body form">
                        @using (Html.BeginForm("Create", "Attendance", FormMethod.Post))
                        {
                            <div class="form-horizontal form-row-sepe">
                                <div class="form-body">
                                    <div class="form-group">
                                        <label class="control-label col-md-2">Title</label>
                                        <div class="col-md-8">
                                            @Html.HiddenFor(x => x.EventID)
                                            @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
                                        </div>
                                    </div>
                                   
                                    <div class="form-group">
                                        <label class="control-label col-md-2">Valid From</label>
                                        <div class="col-md-3">
                                            @Html.TextBoxFor(x => x.ValidStartDate, new { @class = "form-control datetime", @Value = Model.ValidStartDate.ToString("dd MMM yyyy HH:mm") })
                                        </div>

                                        @Html.Label("to", new { @class = "control-label col-md-1", @style = "text-align:center" })

                                        <div class="col-md-4">
                                            @Html.TextBoxFor(x => x.ValidEndDate, new { @class = "form-control datetime", @Value = Model.ValidEndDate.ToString("dd MMM yyyy HH:mm") })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="form-actions right col-md-12">
                                            <a class="btn blue" data-toggle="modal" href="#ConfirmUpdate">
                                                <i class="fa fa-check"></i>
                                                Create
                                            </a>
                                        </div>
                                    </div>
                                    <div class="modal fade" id="ConfirmUpdate" tabindex="-1" role="basic" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                                    <h4 class="modal-title">Confirmation</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <div class="well">
                                                        Clicking Create will create this record into the database with the latest information. If you want to discard the changes, click Close.
                                                    </div>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="submit" class="btn default blue" id="btnUpdateAccount">
                                                        <i class="fa fa-check"></i>
                                                        Create
                                                    </button>
                                                    <button type="button" class="btn default" data-dismiss="modal">Close</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>

                            </div>

                        }


                    </div>
                    <!--END NOTIFICATION HISTORY-->
                </div>
            </div>
        </div>


    </div>
</div>


<script>
    $(".datetime").datetimepicker({
        autoclose: true,
        isRTL: App.isRTL(),
        format: "dd M yyyy hh:ii",
        pickerPosition: (App.isRTL() ? "bottom-right" : "bottom-left")
    });
</script>

Views/Attendance/Detail.cshtml
@model EventManagement.Models.AttendanceQRModel



<div class="note note-info">
    <h4 class="block">
        Event Attendance
    </h4>
    <a href="/Event/Detail/@Model.EventID" class="btn blue btn-sm">Back to Event</a>
</div>

@Html.Action("EventSummary", "Event", new { ID = Model.EventID })


<div class="portlet box blue tabbable">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-reorder"></i>Event Attendance Details
        </div>
    </div>
    <div class="portlet-body form">
        <div class=" portlet-tabs">

            <div class="tab-content">

                <div class="tab-pane active" id="support_detail">
                    <!--START NOTIFICATION HISTORY-->
                    <div class="portlet-body form">

                        <div class="form-horizontal form-row-sepe">
                            <div class="form-body">
                                @using (Html.BeginForm("Edit", "Attendance", FormMethod.Post))
                                {
                                    <div class="row">
                                        <div class="col-md-3">
                                            <img src="@Model.QRCodeImg" style="height:150px" />
                                           
                                        </div>
                                        <div class="col-md-9">



                                            <div class="form-group">
                                                <label class="control-label col-md-2">Title</label>
                                                <div class="col-md-8">
                                                    @Html.HiddenFor(x => x.id)
                                                    @Html.HiddenFor(x => x.EventID)
                                                    @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label col-md-2">Valid From</label>
                                                <div class="col-md-3">
                                                    @Html.TextBoxFor(x => x.ValidStartDate, new { @class = "form-control datetime", @Value = Model.ValidStartDate.AddHours(8).ToString("dd MMM yyyy HH:mm") })
                                                </div>

                                                @Html.Label("to", new { @class = "control-label col-md-1", @style = "text-align:center" })

                                                <div class="col-md-4">
                                                    @Html.TextBoxFor(x => x.ValidEndDate, new { @class = "form-control datetime", @Value = Model.ValidEndDate.AddHours(8).ToString("dd MMM yyyy HH:mm") })
                                                </div>
                                            </div>

                                        </div>

                                    </div>


                                    <div class="form-group">
                                        <div class="form-actions right col-md-12">
                                            <a class="btn blue" data-toggle="modal" href="#ConfirmUpdate">
                                                <i class="fa fa-check"></i>
                                                Update
                                            </a>
                                        </div>
                                    </div>
                                    <div class="modal fade" id="ConfirmUpdate" tabindex="-1" role="basic" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                                    <h4 class="modal-title">Confirmation</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <div class="well">
                                                        Clicking Update will Update this record into the database with the latest information. If you want to discard the changes, click Close.
                                                    </div>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="submit" class="btn default blue" id="btnUpdateAccount">
                                                        <i class="fa fa-check"></i>
                                                        Update
                                                    </button>
                                                    <button type="button" class="btn default" data-dismiss="modal">Close</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                }
                            </div>
                        </div>

                    </div>
                    <!--END NOTIFICATION HISTORY-->
                </div>
            </div>
        </div>


    </div>
</div>


<script>
    $(".datetime").datetimepicker({
        autoclose: true,
        isRTL: App.isRTL(),
        format: "dd M yyyy hh:ii",
        pickerPosition: (App.isRTL() ? "bottom-right" : "bottom-left")
    });
</script>

Views/Attendance/Index.cshtml
@model List<EventManagement.Models.AttendanceQRModel>
@{
    Layout = "";
}
<table id="tblAttendance" class="table table-striped table-bordered table-hover table-full-width">
    <thead>
        <tr>
            <td></td>

            <th>Title</th>

            <th>Valid Start Date</th>
            <th>Valid End Date</th>

            <th>Date</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            <tr>
                <td>
                    <a class="btn blue" href="@Url.Action("Detail", new { ID = item.id })">
                        <i class="fa fa-edit"></i>
                    </a>

                    <a class="btn green" href="@Url.Action("Export", new { ID = item.id, Title = item.Title })">
                        <i class="fa fa-download"></i>
                    </a>

                    <a class="btn red" href="@Url.Action("Delete", new { ID = item.id, EventID = item.EventID })">
                        <i class="fa fa-cut"></i>
                    </a>
                </td>


                <td>@item.Title</td>

                <td>
                    @item.ValidStartDate.AddHours(8).ToString("dd MMM yyyy HH:mm:ss")
                </td>
                <td>
                    @item.ValidStartDate.AddHours(8).ToString("dd MMM yyyy HH:mm:ss")
                </td>
                <td>
                    <div>M: @Html.DisplayFor(modelItem => item.ModifiedBy) - @item.ModifiedDate.ToString("dd MMM yyyy HH:mm:ss")</div>
                    <div>C: @Html.DisplayFor(modelItem => item.CreatedBy) - @item.CreatedDate.ToString("dd MMM yyyy HH:mm:ss")</div>
                </td>
            </tr>
        }
    </tbody>
</table>


<script>
    $(document).ready(function () {

        $("#tblAttendance").dataTable();
        var tableWrapper = "#tblAttendance_wrapper";
        jQuery(tableWrapper + ' .dataTables_filter input').addClass("form-control input-medium input-inline"); // modify table search input
        jQuery(tableWrapper + ' .dataTables_length select').addClass("form-control input-small"); // modify table per page dropdown
        jQuery(tableWrapper + ' .dataTables_length select').select2({
            showSearchInput: false //hide search box with special css class
        });
        jQuery(tableWrapper + ' .dataTables_filter').addClass("pull-right");


    });


</script>